version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    env_file:
      - docker.env
  database:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    env_file:
      - docker.env
    restart: always